FacebookClone/Models/FaceNETModels/UserProfile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FacebookClone.Models.FaceNETModels
{
    public class UserProfile
    {
        public UserProfile()
        {
            UserId = "-1";
            FirstName = "pastaie";
            LastName = "gigi";
            SexId = 0;
            IsPublic = true;
            ImagePath = "../../Images/DefaultMan.jpg";
        }

        public UserProfile(string userId, string firstName, string lastName, int sexId, bool isPublic, string imagePath)
        {
            UserId = userId;
            FirstName = firstName;
            LastName = lastName;
            SexId = sexId;
            IsPublic = isPublic;

            if (imagePath == null)
            { 
                if (SexId == 1)
                    ImagePath = "../../Images/DefaultMan.jpg";
                else
                    ImagePath = "../../Images/DefaultWoman.jpg";
            }
            else
            {
                ImagePath = imagePath;
            }
        }

        public string FullName()
        {
            return FirstName + " " + LastName;
        }

        [Key]
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int SexId { get; set; }
        public bool IsPublic { get; set; }
        public string ImagePath { get; set; }
        
        public virtual ICollection<PhotoAlbum> PhotoAlbums { get; set;  } 
    }

}

FacebookClone/Controllers/MyUserProfileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FacebookClone.Models.FaceNETModels;
using Microsoft.AspNet.Identity;

namespace FacebookClone.Controllers
{
    public class MyUserProfileController : Controller
    {
        private FaceNETDbContext db = new FaceNETDbContext();

        // GET: MyProfile
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                // TO DO 
                // redirect to login page
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var UserId = User.Identity.GetUserId();
            UserProfile MyUserProfile = db.UserProfiles.Find(UserId);

            if (MyUserProfile == null)
            {
                return HttpNotFound();
            }
            return View(MyUserProfile);
        }

        // GET: MyUserProfile/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // GET: MyUserProfile/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // POST: MyUserProfile/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,FirstName,LastName,SexId,IsPublic, ImagePath")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                userProfile.ImagePath = "../../Images/" + userProfile.ImagePath;
                db.Entry(userProfile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userProfile);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AddPhotoAlbum(string userId)
        {
            return View();
        }


        [HttpPost]
        public ActionResult AddPhotoAlbum(PhotoAlbum photoAlbum)
        {
            photoAlbum.UserProfileId = User.Identity.GetUserId();

            db.PhotoAlbums.Add(photoAlbum);

            db.SaveChanges();

            return View();
        }



        public ActionResult AddPhotoToAlbum(int albumId)
        {
            var photoModel = new Photo();
            photoModel.PhotoAlbumId = albumId;

            return View(photoModel);
        }


        [HttpPost]
        public ActionResult AddPhotoToAlbum(Photo photo)
        {

            photo.Path = "../../Images/" + photo.Path;

            db.Photos.Add(photo);

            db.SaveChanges();

            return View();
        }

        public ActionResult DeletePhotoAlbum(int albumId)
        {
            var photosToBeDeleted = db.Photos.Where(c => c.PhotoAlbumId == albumId).ToList();

            db.Photos.RemoveRange(photosToBeDeleted);

            var photoAlbumToBeDeleted = db.PhotoAlbums.FirstOrDefault(c => c.AlbumId == albumId);

            db.PhotoAlbums.Remove(photoAlbumToBeDeleted);

            db.SaveChanges();


            if (User.IsInRole("Administrator"))
            {
                return RedirectToAction("Index", "UserProfiles", new { area = "" });
            }

            return RedirectToAction("Index");
        }


        public ActionResult ConfirmRequest(int id)
        {
            var friendReq = db.FriendRequests.First(c => c.FriendRequestId == id);
            friendReq.IsAccepted = true;
            db.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

FacebookClone/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FacebookClone.Models.FaceNETModels;
using FacebookClone.Models.BusinessLayer;

namespace FacebookClone.Controllers
{
    public class UserProfilesController : Controller
    {
        private FaceNETDbContext db = new FaceNETDbContext();

        // GET: UserProfiles
        public ActionResult Index()
        {
            return View(db.UserProfiles.ToList());
        }

        // GET: UserProfiles/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // GET: UserProfiles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,FirstName,LastName,SexId,IsPublic")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(userProfile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userProfile);
        }

        // GET: UserProfiles/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,FirstName,LastName,SexId,IsPublic")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userProfile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userProfile);
        }

        // GET: UserProfiles/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // POST: UserProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserProfile userProfile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userProfile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




        public ActionResult AddFriend(string requesterId, string requestedId)
        {
            if (!ProfileOfUserHelper.RequestIsSent(requestedId, requesterId))
            {

                var friendReq = new FriendRequest();
                friendReq.RequestedId = requestedId;
                friendReq.RequesterId = requesterId;
                friendReq.IsAccepted = false;

                db.FriendRequests.Add(friendReq);
                db.SaveChanges();
            }

            return RedirectToAction("Details", "UserProfiles", new { id = requestedId });
        }

    }
}

FacebookClone/Views/UserProfiles/Create.cshtml
@model FacebookClone.Models.FaceNETModels.UserProfile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserProfile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SexId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SexId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SexId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPublic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPublic)
                    @Html.ValidationMessageFor(model => model.IsPublic, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FacebookClone/Views/UserProfiles/Delete.cshtml
@model FacebookClone.Models.FaceNETModels.UserProfile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SexId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SexId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPublic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPublic)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FacebookClone/Views/UserProfiles/Details.cshtml
@model FacebookClone.Models.FaceNETModels.UserProfile
@using FacebookClone.Models.BusinessLayer
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "My Profile";
    Layout = "~/Views/Shared/_LayoutAndChatbox.cshtml";
}


<h2 style="font-weight:bold; font-family:'Times New Roman', Times, serif">
    @Model.FirstName @Model.LastName
</h2>


<div>
    <hr />

    <div class="row" style="margin:20px; padding:10px;">
        @if (User.Identity.IsAuthenticated &&
            !ProfileOfUserHelper.UsersAreFriends(User.Identity.GetUserId(), Model.UserId) &&
            !ProfileOfUserHelper.RequestIsSent(Model.UserId, User.Identity.GetUserId()) && 
            !User.IsInRole("Administrator"))
        {
            <div class="btn btn-default">
                <div class="glyphicon glyphicon-user"></div>
                @Html.ActionLink("Add Friend", "AddFriend", new { requesterId = User.Identity.GetUserId() , requestedId = Model.UserId})
            </div>
        }

        @if (ProfileOfUserHelper.RequestIsSent(User.Identity.GetUserId(), Model.UserId))
        {

            <div class="btn btn-default">
                <div class="glyphicon glyphicon-ok-circle" style="color:cornflowerblue"> Friend Request pending</div>
            </div>

        }

        @if (ProfileOfUserHelper.UsersAreFriends(User.Identity.GetUserId(), Model.UserId))
        {

            <div class="btn-default">
                <div class="glyphicon glyphicon-check" style="color:green"> Friends </div>
            </div>
        }



    </div>
    <div class="row">
        <div class="col-md-4">
            <figure>
                <img src="@Url.Content(Model.ImagePath)" alt="IMAGES" style="width:360px; height:240px" />
            </figure>
        </div>
        <dl class="dl-horizontal col-md-4">

            <div style="margin-bottom:1px;">
                <span style="font-size:medium; font-style:oblique; "> Gender : </span>
                @if (Model.SexId == 1)
                {
                    <div class="glyphicon glyphicon-king">  Male  </div>
                }
                @if (Model.SexId == 2)
                {
                    <div class="glyphicon glyphicon-queen">  Female  </div>
                }
            </div>

            </br>


            <div style="margin-bottom:1px;">
                <span style="font-size:medium; font-style:oblique"> Public profile : </span>
                @if (Model.IsPublic)
                {
                    <div class="glyphicon glyphicon-check" style="color:green">  Yes </div>
                }
                @if (!Model.IsPublic)
                {
                    <div class="glyphicon glyphicon-remove" style="color:red">  No </div>
                }
            </div>


            </br>


            <div style="margin-bottom:1px;">
                <span style="font-size:medium; font-style:oblique"> No. of Friends : </span> @ProfileOfUserHelper.GetFriendsOfUserByUserId(Model.UserId).Count()

            </div>

        </dl>
        <div class="col-md-4">
            <span style="font-weight:bold; font-size:22px;">Friends</span>
            @{ 
                var friends = ProfileOfUserHelper.GetFriendsOfUserByUserId(Model.UserId);
                foreach(var friend in friends)
                {
                    <div>
                        @friend.FirstName @friend.LastName
                    </div>
                }
            }
        </div>
    </div>

    <div class="row" style="margin-top:20px">

        @foreach (var photoAlbum in Model.PhotoAlbums)
            {
            <div class="row" style=" overflow-x:hidden;margin-bottom:50px; padding:10px; border:2px solid black; border-radius: 50px 20px;">

                <div class="row " style="border-bottom:2px solid black; margin-bottom:5px; padding:10px;">

                    <div class="col-md-10 text-center" style="font-weight:bold; ">
                        @photoAlbum.Name
                    </div>


                    @if (User.IsInRole("Administrator"))
                    {

                        <div class="btn btn-danger pull-right">
                            <div class="glyphicon glyphicon-trash"></div>
                            @Html.ActionLink("Delete Album", "DeletePhotoAlbum", "MyUserProfile", new { albumId = photoAlbum.AlbumId}, null)
                       </div>

                    }
                </div>




                @foreach (var photo in photoAlbum.Photos)
                {
                    <div class="col-md-4 center-block" style="margin-bottom:20px;">
                        <figure>
                            <img src="@Url.Content(photo.Path)" alt="IMAGES" style="width:360px; height:240px" />
                            <figcaption>
                                @photo.Description
                            </figcaption>
                        </figure>
                    </div>
                }

                @if (photoAlbum.Photos == null || photoAlbum.Photos.Count() == 0)
                {
                    <div class="text-center" style="font-size:12px; font-style:italic;">
                        No available photos in this album.
                    </div>
                }

            </div>
        }

    </div>
</div>

FacebookClone/Views/UserProfiles/Edit.cshtml
@model FacebookClone.Models.FaceNETModels.UserProfile

@{
    ViewBag.Title = "Edit";
}

@using FacebookClone.Models.ModelsDTO
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserProfile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SexId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <select class="form-control" id="SexId" name="SexId">
                    <option>Select Gender</option>
                    <option value="1">Male</option>
                    <option value="2">Female</option>
                </select>

                @Html.ValidationMessageFor(model => model.SexId, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.IsPublic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPublic)
                    @Html.ValidationMessageFor(model => model.IsPublic, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FacebookClone/Views/UserProfiles/Index.cshtml
@model IEnumerable<FacebookClone.Models.FaceNETModels.UserProfile>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SexId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPublic)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SexId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsPublic)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserId })
        </td>
    </tr>
}

</table>